package com.sergo_smyk.downloader.api

import android.app.DownloadManager as DM

enum class DownloadReason(val code: Int) {
    NONE(-1),
    ERROR_UNKNOWN(DM.ERROR_UNKNOWN),
    ERROR_FILE_ERROR(DM.ERROR_FILE_ERROR),
    ERROR_UNHANDLED_HTTP_CODE(DM.ERROR_UNHANDLED_HTTP_CODE),
    ERROR_HTTP_DATA_ERROR(DM.ERROR_HTTP_DATA_ERROR),
    ERROR_TOO_MANY_REDIRECTS(DM.ERROR_TOO_MANY_REDIRECTS),
    ERROR_INSUFFICIENT_SPACE(DM.ERROR_INSUFFICIENT_SPACE),
    ERROR_DEVICE_NOT_FOUND(DM.ERROR_DEVICE_NOT_FOUND),
    ERROR_CANNOT_RESUME(DM.ERROR_CANNOT_RESUME),
    ERROR_FILE_ALREADY_EXISTS(DM.ERROR_FILE_ALREADY_EXISTS),
    PAUSED_WAITING_TO_RETRY(DM.PAUSED_WAITING_TO_RETRY),
    PAUSED_WAITING_FOR_NETWORK(DM.PAUSED_WAITING_FOR_NETWORK),
    PAUSED_QUEUED_FOR_WIFI(DM.PAUSED_QUEUED_FOR_WIFI),
    PAUSED_UNKNOWN(DM.PAUSED_UNKNOWN);

    companion object {
        fun get(reason: Int): DownloadReason {
            return DownloadReason.values().firstOrNull { it.code == reason } ?: NONE
        }
    }
}